apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-pv
spec:
  storageClassName: local-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data"
