apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: react-deploy
spec:
  params:
    - name: repo-url
    - name: deployment-name
    - name: image
    - name: docker-username
    - name: docker-password
  workspaces:
    - name: source
  tasks:
    - name: source-clone
      taskRef: 
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: code
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: source
    - name: gitops-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/UsmanAsim/tekton-react-gitops.git 
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: gitops
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: source
      runAfter:
        - source-clone

    - name: install
      taskRef:
        name: npm
      params:
        - name: ARGS
          value: 
            - install
      workspaces:
        - name: source
          workspace: source
          subPath: code
      runAfter:
        - gitops-clone
    - name: run
      taskRef:
        name: npm
      params:
        - name: ARGS
          value: 
            - run 
      workspaces:
        - name: source
          workspace: source
          subPath: code
      runAfter:
        - install
    - name: build-push
      taskRef:
        name: build-push
      params:
        - name: image
          value: $(params.image)
        - name: username
          value: $(params.docker-username)
        - name: password
          value: $(params.docker-password)
      workspaces:
        - name: source
          workspace: source
          subPath: code
      runAfter:
        - run
    - name: deploy
      taskRef:
        name: kubernetes-actions
      params:
        - name: args
          value: 
            - rollout 
            - restart 
            - deployment/$(params.deployment-name)
      runAfter:
        - build-push
